import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createRequire} from 'node:module';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright'),out=process.env.PIP_BATCH_QA_OUTPUT||fs.mkdtempSync(path.join(os.tmpdir(),'routing-ui-'));fs.mkdirSync(out,{recursive:true});
Object.assign(process.env,{NODE_ENV:'test',DATABASE_URL:'',OPENAI_API_KEY:'',PIP_AI_DISABLED:'true',PIP_MEMORY_FILE:path.join(out,'routing-ui.memory.json'),PIP_APPROVED_TRAINING_FILE:path.join(out,'training.md'),PIP_BRIDGE_SECRET:'routing-ui-local',PIP_ALLOWED_ORIGINS:'http://127.0.0.1:4199',DOTENV_CONFIG_PATH:path.join(out,'absent.env')});
const m=await import('./pipMemory.js');m.resetMemoryForTests();const {app}=await import('./index.js');const {issuePipSession}=await import('./pipAuth.js');const server=await new Promise(resolve=>{const s=app.listen(4199,'127.0.0.1',()=>resolve(s))}),base='http://127.0.0.1:4199';
const member={id:'conversation-ui-owner',name:'Fictional grower'},subscription={active:true,plan:'pip_pro'},token=issuePipSession({member,subscription}),other={id:'conversation-ui-other',name:'Other grower'},otherToken=issuePipSession({member:other,subscription});
const profile={crops:['lettuce'],growZone:'9b',onboardingComplete:true};const project=(await m.createProject({user:member,subscription,type:'hydropip_build',title:'Routing Alpha',systemProfile:profile})).project,second=(await m.createProject({user:member,subscription,type:'hydropip_build',title:'Greenhouse Beta',systemProfile:profile})).project;
await m.seedProjectConversationDefaults({userId:member.id,projectId:project.id,subscription});const threads=await m.listProjectConversations({userId:member.id,projectId:project.id}),seed=threads.find(x=>x.summary==='starter:seeds_germination'),maintenance=threads.find(x=>x.summary==='starter:maintenance'),feeding=threads.find(x=>x.summary==='starter:feeding_nutrients');
const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:1440,height:980}}),page=await context.newPage(),errors=[],results=[];await context.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());page.on('pageerror',error=>errors.push(error.message));
async function check(name,run){try{await run();results.push({name,pass:true});console.log('PASS '+name)}catch(error){results.push({name,pass:false,error:error.stack});console.error('FAIL '+name+' '+error.stack+'\n'+JSON.stringify({errors,body:(await page.locator('body').innerText()).slice(-4000)}));await page.screenshot({path:path.join(out,'routing-ui-failure.png')});throw error}}
const until=async fn=>{for(let i=0;i<200;i++){if(await fn())return;await new Promise(r=>setTimeout(r,40))}throw Error('Timed out waiting for browser state')};
async function start(projectId=project.id){await page.goto(base+'/pip.html?projectId='+projectId);await page.evaluate(data=>window.postMessage(data,location.origin),{type:'HYDROPIP_PIP_SESSION',sessionToken:token,member,subscription});await until(async()=>await page.locator('#pipConversationSelect option').count()>=8)}
async function select(id){await page.locator('#pipConversationSelect').selectOption(id);await until(async()=>await page.locator('#pipConversationSelect').inputValue()===id);await page.waitForTimeout(70)}
async function ask(question){await page.locator('#pipInput').fill(question);await page.locator('#pipForm button[type=submit]').click()}
const messages=conversationId=>m.listProjectMessages({userId:member.id,projectId:project.id,conversationId,limit:200});
try{
 await check('Clear subject change routes question and answer with visible destination and Undo',async()=>{
  await start();await select(seed.id);await ask('How should I clean my pump?');await until(async()=>await page.locator('#pipConversationSelect').inputValue()===maintenance.id&&(await page.locator('.conversation-filing').innerText()).includes('Saved in Maintenance'));
  assert.equal((await messages(maintenance.id)).length,2);assert.equal((await messages(seed.id)).length,0);assert.equal(await page.locator('#pipLog .msg.user').count(),1);await page.screenshot({path:path.join(out,'routing-desktop.png')});
 });
 await check('Undo restores the exchange; reload keeps it in the corrected thread',async()=>{
  await page.locator('.conversation-filing').getByRole('button',{name:'Undo',exact:true}).click();await until(async()=>await page.locator('#pipConversationSelect').inputValue()===seed.id&&(await messages(seed.id)).length===2);await start();assert.equal(await page.locator('#pipConversationSelect').inputValue(),seed.id);await until(async()=>await page.locator('#pipLog .msg.user').count()===1);assert.match(await page.locator('#pipLog').innerText(),/How should I clean my pump/);
 });
 await check('Short follow-up stays in the current exchange topic',async()=>{
  await ask('How much?');await until(async()=>(await messages(seed.id)).length===4);assert.equal(await page.locator('#pipConversationSelect').inputValue(),seed.id);await until(async()=>await page.locator('#pipLog .msg.user').count()===2);
 });
 await check('Ambiguous subject retains draft and asks before sending',async()=>{
  const before=(await messages(seed.id)).length;await ask('Explain nutrients and harvesting');await page.locator('.conversation-dialog[open]').waitFor();assert.equal(await page.locator('#pipInput').inputValue(),'Explain nutrients and harvesting');assert.equal((await messages(seed.id)).length,before);
  await page.locator('.conversation-dialog select').selectOption({label:'Feeding & Nutrients'});await page.locator('.conversation-dialog').getByRole('button',{name:'Continue',exact:true}).click();await until(async()=>await page.locator('#pipConversationSelect').inputValue()===feeding.id&&(await messages(feeding.id)).length===2);
 });
 await check('Unavailable routing preserves photo and draft when choice is canceled',async()=>{
  await page.route('**/conversations/route',route=>route.fulfill({status:503,contentType:'application/json',body:'{"message":"Test routing outage"}'}));
  await page.locator('#pipPhoto').setInputFiles({name:'test-seed.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6B3sAAAAASUVORK5CYII=','base64')});await until(async()=>(await page.locator('#pipPhotoName').innerText()).includes('Pip will examine'));
  await ask('Please inspect this photo');await page.locator('.conversation-dialog[open]').waitFor();await page.locator('.conversation-dialog').getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.locator('#pipInput').inputValue(),'Please inspect this photo');assert.equal(await page.locator('#pipPhotoPreview').isVisible(),true);await page.locator('#pipPhotoRemove').click();await page.unroute('**/conversations/route');
 });
 await check('Delayed old reply cannot replace a newly selected conversation',async()=>{
  let release,finished;const gate=new Promise(resolve=>{release=resolve}),delivered=new Promise(resolve=>{finished=resolve});let received=false;await page.route('**/api/pip/chat',async route=>{const response=await route.fetch();received=true;await gate;await route.fulfill({response});finished()});
  await ask('How should I clean my pump?');await until(()=>received);await select(seed.id);release();await delivered;await page.unroute('**/api/pip/chat');await page.waitForTimeout(120);assert.equal(await page.locator('#pipConversationSelect').inputValue(),seed.id);assert.equal(await page.locator('#pipLog .msg.user').count(),2);
 });
 await check('History loads older messages and finds a record beyond the initial page',async()=>{
  for(let i=0;i<45;i++)await m.appendProjectMessage({userId:member.id,projectId:project.id,conversationId:seed.id,role:i%2?'assistant':'user',content:i===0?'Unique old Marconi pepper record':'Historical message '+i});await start();await select(seed.id);await page.getByRole('button',{name:'Load older messages',exact:true}).click();await until(async()=>(await page.locator('#pipLog').innerText()).includes('Unique old Marconi'));
  await page.getByRole('button',{name:'Search & archives',exact:true}).click();await page.getByRole('searchbox',{name:'Search saved messages'}).fill('Marconi');await page.locator('.conversation-dialog').getByRole('button',{name:'Search',exact:true}).click();await until(async()=>(await page.locator('#conversationSearchResults').innerText()).includes('Unique old Marconi'));await page.screenshot({path:path.join(out,'history-search.png')});await page.locator('.conversation-dialog').getByRole('button',{name:'Close',exact:true}).click();
 });
 await check('Archived conversations can be browsed and restored',async()=>{
  await m.updateProjectConversation({userId:member.id,projectId:project.id,conversationId:feeding.id,patch:{status:'archived'},subscription});await page.getByRole('button',{name:'Search & archives',exact:true}).click();await page.getByRole('button',{name:'Browse archived conversations',exact:true}).click();await page.locator('.conversation-dialog').getByRole('button',{name:'Restore conversation',exact:true}).click();await until(async()=>await page.locator('#pipConversationSelect').inputValue()===feeding.id);assert.equal((await m.listProjectConversations({userId:member.id,projectId:project.id})).find(x=>x.id===feeding.id).status,'active');
 });
 await check('Manual Move exchange keeps the answer together and supports Undo',async()=>{
  await page.locator('#pipLog .exchange-controls').first().getByRole('button',{name:'Move exchange'}).click();await page.locator('.conversation-dialog select').selectOption({label:'Seeds & Germination'});await page.locator('.conversation-dialog').getByRole('button',{name:'Continue',exact:true}).click();await until(async()=>await page.locator('#pipConversationSelect').inputValue()===seed.id&&(await page.locator('.conversation-filing').innerText()).includes('Moved to'));
  await page.locator('.conversation-filing').getByRole('button',{name:'Undo',exact:true}).click();await until(async()=>await page.locator('#pipConversationSelect').inputValue()===feeding.id);
 });
 await check('Older mixed conversation offers a preview and applies only selected moves',async()=>{
  const mixed=(await m.createProjectConversation({userId:member.id,projectId:project.id,title:'Old mixed notes',subscription})).conversation;for(const [role,content] of [['user','How should I clean my pump?'],['assistant','Old cleaning answer'],['user','How much MasterBlend do I need?'],['assistant','Old nutrient answer']])await m.appendProjectMessage({userId:member.id,projectId:project.id,conversationId:mixed.id,role,content});await start();await select(mixed.id);await page.getByRole('button',{name:'Organize this conversation'}).click();await page.locator('.conversation-dialog[open]').waitFor();const choices=page.locator('.conversation-organize-item input');assert.equal(await choices.count(),2);assert.equal((await messages(mixed.id)).length,4);await choices.first().check();await page.getByRole('button',{name:'Apply selected moves'}).click();await until(async()=>(await messages(mixed.id)).length===2);assert.ok((await messages(mixed.id)).some(x=>x.content.includes('MasterBlend')));await page.getByRole('button',{name:'Undo move',exact:true}).click();await until(async()=>(await messages(mixed.id)).length===4);await page.locator('.conversation-dialog').getByRole('button',{name:'Close',exact:true}).click();
 });
 await check('Phone layout keeps routing notice and history controls usable',async()=>{
  await page.setViewportSize({width:390,height:844});await select(seed.id);await ask('How should I clean my pump?');await until(async()=>(await page.locator('.conversation-filing').innerText()).includes('Saved in Maintenance'));assert.ok(await page.locator('.conversation-filing').isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await page.screenshot({path:path.join(out,'routing-mobile.png')});
 });

 await check('A named different grow requires confirmation before changing context',async()=>{
  await page.setViewportSize({width:1440,height:980});await start();await select(seed.id);await ask('How should I clean my pump in Greenhouse Beta?');await page.locator('.conversation-dialog[open]').waitFor();assert.equal(await page.locator('#pipConversationSelect').inputValue(),seed.id);await page.locator('.conversation-dialog select').selectOption({label:'Greenhouse Beta'});await page.locator('.conversation-dialog').getByRole('button',{name:'Continue',exact:true}).click();await until(async()=>(await page.locator('.conversation-filing').innerText()).includes('Saved in Maintenance'));const saved=await m.listProjectConversations({userId:member.id,projectId:second.id});const destination=saved.find(x=>x.title==='Maintenance & Cleaning');assert.ok(destination);assert.equal((await m.listProjectMessages({userId:member.id,projectId:second.id,conversationId:destination.id})).length,2);
  await page.locator('.conversation-filing').getByRole('button',{name:'Undo',exact:true}).click();await until(async()=>(await m.listProjectMessages({userId:member.id,projectId:second.id,conversationId:destination.id})).length===0);assert.notEqual(await page.locator('#pipConversationSelect').inputValue(),destination.id);
 });
 await check('A lost response retries the same exchange and displays one saved pair',async()=>{
  await start();await select(seed.id);let first=true,ids=[];await page.route('**/api/pip/chat',async route=>{ids.push(route.request().postDataJSON().exchangeId);if(first){first=false;await route.fetch();await route.abort()}else await route.continue()});await ask('How should I clean my pump?');await page.getByRole('button',{name:'Retry exchange',exact:true}).click();await until(async()=>(await page.locator('.conversation-filing').innerText()).includes('Saved in Maintenance'));await page.unroute('**/api/pip/chat');assert.equal(ids.length,2);assert.equal(ids[0],ids[1]);assert.equal((await messages(maintenance.id)).filter(x=>x.exchangeId===ids[0]).length,2);
 });
 await check('A late routing decision preserves the photo when canceled',async()=>{
  await select(seed.id);await page.locator('#pipPhoto').setInputFiles({name:'late-photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6B3sAAAAASUVORK5CYII=','base64')});await until(async()=>(await page.locator('#pipPhotoName').innerText()).includes('Pip will examine'));
  await page.route('**/api/pip/chat',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'route_choice_required',route:{message:'A matching topic changed. Choose where to send.',choices:[seed,maintenance]}})}));await ask('How should I clean my pump?');await page.locator('.conversation-dialog[open]').waitFor();await page.locator('.conversation-dialog').getByRole('button',{name:'Cancel',exact:true}).click();await until(async()=>await page.locator('#pipPhotoPreview').isVisible());assert.equal(await page.locator('#pipInput').inputValue(),'How should I clean my pump?');await page.unroute('**/api/pip/chat');await page.locator('#pipPhotoRemove').click();
 });
 await check('A delayed routing response cannot send a prior member draft into a new account',async()=>{
  const otherProject=(await m.createProject({user:other,subscription,type:'hydropip_build',title:'Other member grow',systemProfile:profile})).project;await m.seedProjectConversationDefaults({userId:other.id,projectId:otherProject.id,subscription});
  let release,done;const gate=new Promise(r=>release=r),delivered=new Promise(r=>done=r);let received=false;await page.route('**/conversations/route',async route=>{const response=await route.fetch();received=true;await gate;await route.fulfill({response});done()});await ask('How should I clean my pump?');await until(()=>received);
  await page.evaluate(data=>window.postMessage(data,location.origin),{type:'HYDROPIP_PIP_SESSION',sessionToken:otherToken,member:other,subscription});await until(async()=>!(await page.locator('#pipConversationSelect option').evaluateAll(items=>items.map(x=>x.value))).includes(seed.id));release();await delivered;await page.unroute('**/conversations/route');await page.waitForTimeout(200);assert.equal(await page.locator('#pipInput').inputValue(),'');assert.ok(!(await page.locator('#pipLog').innerText()).includes('How should I clean my pump?'));assert.equal((await m.listProjectMessages({userId:other.id,projectId:otherProject.id,limit:200})).length,0);
  await start();await select(seed.id);
 });
 await check('A second browser context loads the same persisted exchange',async()=>{
  const secondContext=await browser.newContext();await secondContext.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue():route.abort());const fresh=await secondContext.newPage();await fresh.goto(base+'/pip.html?projectId='+project.id);await fresh.evaluate(data=>window.postMessage(data,location.origin),{type:'HYDROPIP_PIP_SESSION',sessionToken:token,member,subscription});await until(async()=>await fresh.locator('#pipConversationSelect option').count()>=8);await fresh.locator('#pipConversationSelect').selectOption(maintenance.id);await until(async()=>(await fresh.locator('#pipLog').innerText()).includes('How should I clean my pump?'));await secondContext.close();
 });
 await check('No browser exceptions in conversation journeys',()=>assert.deepEqual(errors,[]));
}finally{fs.writeFileSync(path.join(out,'conversation-ui-results.json'),JSON.stringify(results,null,2));await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r))}
console.log(results.length+' conversation browser acceptance checks passed.');
