import {createHash,randomUUID} from 'node:crypto';
import {conversationStorage,normalizeSeed} from './pipMemory.js';
import {getSeedSowRecommendation} from './plantingCalendar.js';

const fail=(message,statusCode=400)=>{throw Object.assign(Error(message),{statusCode})};
const past=s=>s.plantingLocation==='finished'||['harvested','finished','failed'].includes(s.status);
const active=s=>s.plantingLocation==='hydropip_tower'&&!past(s);
const canonical=v=>Array.isArray(v)?v.map(canonical):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])])):v;
const hash=v=>createHash('sha256').update(JSON.stringify(canonical(v))).digest('hex');
const integer=(v,min,max)=>Number.isInteger(Number(v))&&Number(v)>=min&&Number(v)<=max;
const today=(timezone='UTC')=>{try{return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}catch{fail('Choose a valid time zone.')}};
function validDay(v){return /^\d{4}-\d{2}-\d{2}$/.test(v||'')&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;}
export function towerShape(p){const towers=Number(p.towerCount),levels=Number(p.levelsPerTower),pots=Number(p.potsPerLevel)||4;return integer(towers,1,40)&&integer(levels,1,20)&&integer(pots,1,8)&&towers*levels*pots<=1600?{towers,levels,pots,capacity:towers*levels*pots}:null;}
function coords(index,shape){return{tower:Math.floor(index/(shape.levels*shape.pots))+1,level:Math.floor(index/shape.pots)%shape.levels+1,face:String.fromCharCode(65+index%shape.pots)};}
function missing(p){const fields={towerArrangement:'tower arrangement',towerSpacingInches:'space between towers',levelSpacingInches:'space between levels',potSpacingInches:'space between pots on a level',potVolumeLiters:'pot volume',lightDirection:'light direction',plantSupports:'plant supports',reservoirConnections:'reservoir connections',medium:'growing medium',pumpSchedule:'feeding schedule',areaType:'growing environment'};return Object.entries(fields).filter(([k])=>['towerSpacingInches','levelSpacingInches','potSpacingInches','potVolumeLiters'].includes(k)?!(Number(p[k])>0&&Number(p[k])<=500):!p[k]).map(([,label])=>label);}
function fingerprint(state){return hash([state.project.systemProfile,[...state.seeds].sort((a,b)=>a.id.localeCompare(b.id))]);}
function recommendation(seed,p,date){
  if(seed.packetWindowStart&&seed.packetWindowEnd&&validDay(seed.packetWindowStart)&&validDay(seed.packetWindowEnd))return {decision:date>=seed.packetWindowStart&&date<=seed.packetWindowEnd?'plant_now':'wait',bestSowDate:date<seed.packetWindowStart?seed.packetWindowStart:null,reason:'Your reviewed packet/local planting window: '+seed.packetWindowStart+' to '+seed.packetWindowEnd,source:'Saved packet/local window'};
  if(/indoor|greenhouse/i.test(p.areaType||''))return {decision:'check',reason:'Outdoor zone dates do not establish indoor readiness. Save a reviewed planting window in Seed Vault.',source:'Indoor conditions need review'};
  const r=getSeedSowRecommendation({crop:seed.crop,growZone:p.growZone,location:p.location,areaType:p.areaType,date});
  return r?.status==='recommended'?{decision:r.decision,bestSowDate:r.bestSowDate,reason:r.reason,source:'Seasonal zone estimate; confirm local conditions',method:r.method}:{decision:'check',reason:'No supported timing window. Add a reviewed planting window in Seed Vault.',source:'Timing not established'};
}
function eligibility(s,p,date){const timing=recommendation(s,p,date),issues=[];if(!(s.plantSpacingInches>0))issues.push('Add mature spacing from the packet or a crop reference in Seed Vault.');if(!s.towerFitReviewed)issues.push('Review this variety’s pot size, light, support and feeding fit in Seed Vault.');if(timing.decision==='check')issues.push(timing.reason);if(/tomato|pepper|cucumber|squash|melon|eggplant/i.test(s.crop)&&(!p.plantSupports||p.plantSupports==='none'))issues.push('This larger crop needs a support plan in Profile.');return {record:s,seedId:s.id,crop:s.crop,variety:s.variety,packsOnHand:s.packsOnHand,spacing:s.plantSpacingInches,timing,issues,eligible:!issues.length};}
function makeView(state){const p=state.project.systemProfile,shape=towerShape(p),date=today(),unmapped=state.seeds.filter(active).filter(s=>!s.towerPositions?.length);return {profile:p,shape,missing:missing(p),fingerprint:fingerprint(state),plan:state.plan?Object.fromEntries(Object.entries(state.plan).filter(([k])=>k!=="undo")):null,undoId:state.plan?.undo?.id||null,existing:state.seeds.filter(active).map(s=>({id:s.id,crop:s.crop,variety:s.variety,positions:s.towerPositions||[],spacing:s.plantSpacingInches,status:s.status})),inventory:state.seeds.filter(s=>(s.plantingLocation||'seed_vault')==='seed_vault').map(s=>eligibility(s,p,date)),unmapped:unmapped.map(s=>({id:s.id,crop:s.crop,variety:s.variety,quantity:s.plantsPlanted||s.seedsSown||null})),stale:!!state.plan&&(state.plan.profileHash!==hash(p)||state.plan.sourceHash!==fingerprint(state)),today:date};}

// Serialize plan mutations with the same grow lock used by reviewed actions.
async function transaction(args,run){
  if(!args.subscription?.active)fail('Tower planning requires Pip Pro.',402);
  const storage=await conversationStorage();
  if(storage.pool){const client=await storage.pool.connect();try{await client.query('begin');const row=(await client.query('select id,user_id,title,system_profile from pip_projects where id=$1 and user_id=$2 for update',[args.projectId,args.userId])).rows[0];if(!row)fail('Grow not found.',404);const seeds=(await client.query('select * from pip_seeds where project_id=$1 and user_id=$2 order by id for update',[args.projectId,args.userId])).rows.map(r=>({...r.seed,id:r.id,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()}));const state={project:{id:row.id,title:row.title,systemProfile:row.system_profile},seeds,plan:(await client.query('select plan from pip_tower_plans where project_id=$1 and user_id=$2',[args.projectId,args.userId])).rows[0]?.plan};const before=structuredClone(state),result=run(state);if(result.write){attachUndo(state,before,result);result.value=makeView(state);await client.query('insert into pip_tower_plans(project_id,user_id,plan) values($1,$2,$3::jsonb) on conflict(project_id) do update set plan=excluded.plan',[args.projectId,args.userId,JSON.stringify(state.plan)]);for(const id of result.deletedSeedIds||[])await client.query('delete from pip_seeds where id=$1 and project_id=$2 and user_id=$3',[id,args.projectId,args.userId]);for(const s of result.seeds||[])await client.query('insert into pip_seeds(id,project_id,user_id,seed,created_at,updated_at) values($1,$2,$3,$4::jsonb,$5,$6) on conflict(id) do update set seed=excluded.seed,updated_at=excluded.updated_at',[s.id,args.projectId,args.userId,JSON.stringify(s),s.createdAt,s.updatedAt]);}await client.query('commit');return result.value;}catch(e){await client.query('rollback');throw e}finally{client.release()}}
  const db=structuredClone(storage.read()),project=db.projects[args.projectId];if(!project||project.userId!==args.userId)fail('Grow not found.',404);const state={project,seeds:[...(db.seeds?.[args.projectId]||[])].sort((a,b)=>a.id.localeCompare(b.id)),plan:db.towerPlans?.[args.projectId]};const before=structuredClone(state),result=run(state);if(result.write){attachUndo(state,before,result);result.value=makeView(state);db.towerPlans||={};db.towerPlans[args.projectId]=state.plan;db.seeds||={};const map=new Map(state.seeds.filter(s=>!(result.deletedSeedIds||[]).includes(s.id)).map(s=>[s.id,s]));for(const s of result.seeds||[])map.set(s.id,s);db.seeds[args.projectId]=[...map.values()];storage.write(db)}return result.value;
}
function attachUndo(state,before,result){
  if(result.undoing||!state.plan)return;
  const changed=new Set((result.seeds||[]).map(s=>s.id));
  const previous=before.plan?structuredClone(before.plan):null;if(previous)delete previous.undo;
  state.plan.undo={id:randomUUID(),fingerprint:fingerprint(state),plan:previous,seeds:before.seeds.filter(s=>changed.has(s.id)),inserted:[...changed].filter(id=>!before.seeds.some(s=>s.id===id))};
}
export const getTowerPlan=args=>transaction(args,state=>({value:makeView(state)}));
function checkVersion(state,args){if(args.baseRevision!==(state.plan?.revision||0))fail('The plan changed on another device. Reload before saving.',409);if(args.fingerprint!==fingerprint(state))fail('Your profile or crop records changed. Reload and review the plan.',409);}
function occupied(state,shape){const map=new Map();for(const seed of state.seeds.filter(active)){for(const index of seed.towerPositions||[]){if(!integer(index,0,shape.capacity-1)||map.has(index))fail('Existing crop positions conflict with this setup. Correct them before planning.',409);map.set(index,seed)}}return map;}
export function buildTowerDraft(state,selection,allowEmpty=false){
  const p=state.project.systemProfile,shape=towerShape(p);if(!shape)fail('Complete tower count, levels and pots per level in Profile.');if(missing(p).length)fail('Complete Profile: '+missing(p).join(', ')+'.');if(state.seeds.some(s=>active(s)&&!s.towerPositions?.length))fail('Assign your existing tower crops before adding new plants.');
  if(!Array.isArray(selection)||(!allowEmpty&&selection.length<1)||selection.length>30)fail('Choose between one and thirty owned varieties.');if(new Set(selection.map(s=>s.seedId)).size!==selection.length)fail('Choose each seed variety once.');
  const used=occupied(state,shape),slots=Array.from({length:shape.capacity},(_,index)=>({index,...coords(index,shape),status:used.has(index)?'growing':'available',cropId:used.get(index)?.id||null,crop:used.get(index)?.crop||null,variety:used.get(index)?.variety||null,spacing:used.get(index)?.plantSpacingInches||null,reason:used.has(index)?'Saved planted crop':'Available; no crop assigned.'}));
  const plants=[...used].map(([index,s])=>({index,spacing:s.plantSpacingInches||null}));if(plants.some(p=>!p.spacing))fail('Existing mapped crops need mature spacing before new positions can be proposed.');
  function conflict(a,b,spacing){const x=coords(a,shape),y=coords(b,shape),required=Math.max(spacing,y.spacing||0);if(x.tower!==y.tower)return Number(p.towerSpacingInches)<required;return (x.face===y.face||Number(p.potSpacingInches)<required)&&Math.abs(x.level-y.level)*Number(p.levelSpacingInches)<required;}
  const unplaced=[],items=[];for(const input of selection){const s=state.seeds.find(s=>s.id===input.seedId&&(s.plantingLocation||'seed_vault')==='seed_vault'&&s.packsOnHand>0);if(!s)fail('A selected packet is no longer in your Seed Vault.',409);if(!integer(input.quantity,1,shape.capacity))fail('Enter a whole-number plant quantity within your system capacity.');const info=eligibility(s,p,today());if(!info.eligible)fail(s.crop+': '+info.issues.join(' '));const status=['plant_now'].includes(info.timing.decision)?'plant_now':'plant_later';items.push({seedId:s.id,crop:s.crop,variety:s.variety,quantity:Number(input.quantity),timing:info.timing,spacing:s.plantSpacingInches});let placed=0;for(const slot of slots){if(placed>=Number(input.quantity))break;if(slot.status!=='available'||slots.some(other=>other.tower===slot.tower&&other.level===slot.level&&other.crop&&((other.seedId&&other.seedId!==s.id)||other.crop!==s.crop||(other.variety||'')!==(s.variety||'')))||plants.some(a=>conflict(a.index,slot.index,Math.max(a.spacing,s.plantSpacingInches))))continue;Object.assign(slot,{status,seedId:s.id,crop:s.crop,variety:s.variety,spacing:s.plantSpacingInches,reason:status==='plant_now'?'Seasonal candidate. Confirm conditions and readiness before planting.':info.timing.reason,plantAfter:info.timing.bestSowDate||null});plants.push({index:slot.index,spacing:s.plantSpacingInches});placed++}if(placed<Number(input.quantity))unplaced.push({crop:s.crop,quantity:Number(input.quantity)-placed,reason:'No remaining position has enough room for the spacing you saved.'});}
  for(const slot of slots)if(slot.status==='available'&&plants.some(a=>conflict(a.index,slot.index,a.spacing))){slot.status='keep_clear';slot.reason='Clearance for a nearby plant’s reviewed mature spacing.';}
  return {revision:(state.plan?.revision||0)+1,profileHash:hash(p),sourceHash:fingerprint(state),profile:p,shape,items,slots,unplaced,createdAt:new Date().toISOString(),receipts:state.plan?.receipts||{},basis:'Positions allow for the mature spacing you saved. Check light, pot/root space, supports and shared feeding before planting.'};
}
export const previewTowerPlan=args=>transaction(args,state=>{checkVersion(state,args);return {value:{draft:buildTowerDraft(state,args.selection),fingerprint:fingerprint(state)}}});
export const saveTowerPlan=args=>transaction(args,state=>{checkVersion(state,args);if(args.confirm!==true)fail('Review the planting plan before saving.');state.plan=buildTowerDraft(state,args.selection);return {write:true,value:makeView(state)}});
export const mapExistingCrop=args=>transaction(args,state=>{checkVersion(state,args);const shape=towerShape(state.project.systemProfile);if(!shape)fail('Complete tower dimensions first.');const seed=state.seeds.find(s=>s.id===args.cropId&&active(s));if(!seed)fail('Current tower crop not found.',404);const indices=args.positions;if(!Array.isArray(indices)||!indices.length||new Set(indices).size!==indices.length||indices.some(i=>!Number.isInteger(i)||!integer(i,0,shape.capacity-1)))fail('Select distinct positions for the existing plants.');if(args.confirm!==true)fail('Confirm existing positions.');const map=occupied({...state,seeds:state.seeds.filter(s=>s.id!==seed.id)},shape);if(indices.some(i=>map.has(i)&&map.get(i).id!==seed.id))fail('A selected position is already growing another crop.',409);const saved=normalizeSeed({...seed,towerPositions:indices,plantsPlanted:indices.length,plantSpacingInches:Number(args.spacing)||seed.plantSpacingInches,updatedAt:new Date().toISOString()});state.seeds=state.seeds.map(s=>s.id===seed.id?saved:s);manualPlan(state);state.plan.revision++;return {write:true,seeds:[saved],value:makeView(state)}});
export const confirmTowerPlanting=args=>transaction(args,state=>{
  if(!args.operationId||!/^[-\w]{8,100}$/.test(args.operationId))fail('A planting operation identifier is required.');if(state.plan?.receipts?.[args.operationId])return {value:makeView(state)};checkVersion(state,args);if(!state.plan)fail('Choose a seed for the level first.');const manualSelection=Array.isArray(args.positions)&&args.positions.length&&args.positions.every(i=>state.plan.slots.find(s=>s.index===i)?.manual);if(!manualSelection&&(state.plan.profileHash!==hash(state.project.systemProfile)||state.plan.sourceHash!==fingerprint(state)))fail('Profile, packets or planted crops changed. Rebuild and review the plan.',409);if(manualSelection)manualPlan(state);if(args.confirm!==true||args.conditionsConfirmed!==true)fail('Confirm that the plants or seeds are in these positions and conditions are suitable.');if(!validDay(args.date)||args.date>today(args.timezone||'UTC'))fail('Enter the actual planting date, not a future date.');if(!['direct_sow','transplant'].includes(args.method))fail('Choose seeds sown or seedlings transplanted.');const indices=args.positions;if(!Array.isArray(indices)||!indices.length||new Set(indices).size!==indices.length)fail('Choose positions planted today.');const occupiedNow=occupied(state,state.plan.shape);const selected=indices.map(i=>state.plan.slots.find(s=>s.index===i));if(selected.some(s=>!s||!['plant_now','plant_later'].includes(s.status)||occupiedNow.has(s.index)))fail('A selected position is no longer available for planting.',409);
  const groups=new Map();for(const slot of selected){const packet=state.seeds.find(s=>s.id===slot.seedId&&(s.plantingLocation||'seed_vault')==='seed_vault');if(!packet)fail('A planned seed packet changed. Review the plan.',409);const info=eligibility(packet,state.project.systemProfile,args.date);if(!slot.manual&&(slot.needsReview||!info.eligible||info.timing.decision!=='plant_now'))fail(packet.crop+': timing or fit still needs review in Seed Vault.');if(!groups.has(packet.id))groups.set(packet.id,{packet,slots:[]});groups.get(packet.id).slots.push(slot)}
  const seeds=[],now=new Date().toISOString();for(const {packet,slots}of groups.values()){const id='seed_'+randomUUID();const saved=normalizeSeed({crop:packet.crop,variety:packet.variety,source:packet.source,packsOnHand:0,id,status:args.method==='transplant'?'growing':'sown',plantingLocation:'hydropip_tower',method:args.method,sowDate:args.method==='direct_sow'?args.date:null,plantedAt:args.date,plantsPlanted:slots.length,seedsSown:args.method==='direct_sow'?slots.length:null,sourceSeedId:packet.id,towerPositions:slots.map(s=>s.index),plantSpacingInches:packet.plantSpacingInches,notes:'Recorded from tower plan. '+(args.method==='direct_sow'?'One seed per selected position; record extra sowing separately.':'Seedling planting date; original sowing date not assumed.'),createdAt:now,updatedAt:now});seeds.push(saved);for(const slot of slots)Object.assign(slot,{status:'growing',cropId:id,reason:'Confirmed planted on '+args.date});}
  state.seeds.push(...seeds);state.plan.sourceHash=fingerprint(state);state.plan.revision++;state.plan.receipts[args.operationId]={at:now,recordIds:seeds.map(s=>s.id)};return {write:true,seeds,value:makeView(state)};
});

export const finishTowerCrop=args=>transaction(args,state=>{checkVersion(state,args);if(args.confirm!==true)fail('Confirm the crop has been removed before releasing its positions.');const crop=state.seeds.find(s=>s.id===args.cropId&&active(s));if(!crop)fail('Current mapped crop not found.',404);const saved=normalizeSeed({...crop,status:'finished',updatedAt:new Date().toISOString()});state.seeds=state.seeds.map(s=>s.id===crop.id?saved:s);if(state.plan){for(const slot of state.plan.slots)if(slot.cropId===crop.id)Object.assign(slot,{status:'available',cropId:null,crop:null,seedId:null,reason:'Crop removed. Rebuild the plan to reuse this space.'});state.plan.revision++;state.plan.sourceHash=fingerprint(state);}return {write:true,seeds:[saved],value:makeView(state)}});
function freshPlan(state){if(state.plan&&(state.plan.profileHash!==hash(state.project.systemProfile)||state.plan.sourceHash!==fingerprint(state)))fail('Saved information changed. Review new suggestions before editing this plan.',409);}
function clearSlot(slot){Object.assign(slot,{status:'available',crop:null,variety:null,cropId:null,seedId:null,spacing:null,reason:'Available; no crop assigned.'});}
function refreshClearance(state){
 const plan=state.plan,p=state.project.systemProfile,shape=plan.shape;
 const crops=new Map(state.seeds.filter(active).map(s=>[s.id,s]));
 for(const s of plan.slots){if(s.status==='keep_clear')clearSlot(s);if(s.status==='growing'){const c=crops.get(s.cropId);if(c)s.spacing=c.plantSpacingInches;}}
 const plants=plan.slots.filter(s=>['growing','plant_now','plant_later'].includes(s.status));
 for(const s of plan.slots.filter(s=>s.status==='available'))if(plants.some(a=>{const d=Number(a.spacing)||0;if(a.tower!==s.tower)return Number(p.towerSpacingInches)<d;return(a.face===s.face||Number(p.potSpacingInches)<d)&&Math.abs(a.level-s.level)*Number(p.levelSpacingInches)<d;})){s.status='keep_clear';s.reason='Leave empty for a nearby plant’s mature spacing.';}
 plan.items=[...new Set(plan.slots.filter(s=>['plant_now','plant_later'].includes(s.status)).map(s=>s.seedId))].map(id=>{const s=state.seeds.find(s=>s.id===id);return{seedId:id,crop:s?.crop,variety:s?.variety,quantity:plan.slots.filter(s=>s.seedId===id&&['plant_now','plant_later'].includes(s.status)).length};});
}
function manualPlan(state){
 const shape=towerShape(state.project.systemProfile);if(!shape)fail('Enter how many towers and how many levels per tower.');
 const owners=occupied(state,shape),stale=!!state.plan&&state.plan.sourceHash!==fingerprint(state),previous=state.plan;
 state.plan={...previous,revision:previous?.revision||0,shape,profile:state.project.systemProfile,profileHash:hash(state.project.systemProfile),sourceHash:fingerprint(state),receipts:previous?.receipts||{},items:previous?.items||[],slots:Array.from({length:shape.capacity},(_,index)=>{const prior=previous?.slots.find(s=>s.index===index),owner=owners.get(index);const slot={index,...coords(index,shape),status:'available',...prior};if(stale&&['plant_now','plant_later'].includes(slot.status)&&!slot.manual)slot.needsReview=true;if(owner)Object.assign(slot,{status:'growing',cropId:owner.id,crop:owner.crop,variety:owner.variety,spacing:owner.plantSpacingInches});else if(slot.status==='growing')clearSlot(slot);return slot;})};return state.plan;
}
export const saveTowerLevel=args=>transaction(args,state=>{
 checkVersion(state,args);if(args.confirm!==true)fail('Confirm your level choice.');const shape=towerShape(state.project.systemProfile);
 if(!shape||!integer(args.tower,1,shape.towers)||!integer(args.level,1,shape.levels)||!integer(args.quantity,0,shape.pots))fail('Choose a valid tower, level and number of pots.');
 const packet=state.seeds.find(s=>s.id===args.seedId&&(s.plantingLocation||'seed_vault')==='seed_vault');if(Number(args.quantity)&&!packet)fail('Choose a seed from your Seed Vault.');
 manualPlan(state);const targets=state.plan.slots.filter(s=>s.tower===Number(args.tower)&&s.level===Number(args.level));
 if(Number(args.quantity)&&targets.some(s=>s.status==='growing'&&(s.crop!==packet.crop||(s.variety||'')!==(packet.variety||''))))fail('Another crop is planted on this level. Move or remove it before choosing a different crop.');
 const free=targets.filter(s=>s.status!=='growing');if(Number(args.quantity)>free.length)fail('This level has '+free.length+' unplanted pots.');
 for(const slot of free)clearSlot(slot);
 for(const slot of free.slice(0,Number(args.quantity)))Object.assign(slot,{status:'plant_now',seedId:packet.id,crop:packet.crop,variety:packet.variety,spacing:packet.plantSpacingInches,manual:true,needsReview:false,reason:'Chosen by you. Saved placement, not a planting-time or spacing recommendation.'});
 refreshClearance(state);state.plan.revision++;return{write:true,value:makeView(state)};
});
export const updateTowerPositions=args=>transaction(args,state=>{
 checkVersion(state,args);manualPlan(state);
 if(args.confirm!==true||!['stage','remove'].includes(args.action))fail('Confirm the crop update.');
 if(args.action==='stage'&&!['sown','germinating','sprouted','growing','harvest_ready','harvesting'].includes(args.stage))fail('Choose a valid growth stage.');
 const indices=args.positions;if(!Array.isArray(indices)||!indices.length||new Set(indices).size!==indices.length||indices.some(i=>!Number.isInteger(i)))fail('Choose the planted pots to update.');
 const owners=occupied(state,state.plan.shape);if(indices.some(i=>!owners.has(i)))fail('A selected pot no longer contains a current plant.',409);
 const updates=[],now=new Date().toISOString();
 for(const id of new Set(indices.map(i=>owners.get(i).id))){const crop=state.seeds.find(s=>s.id===id),chosen=crop.towerPositions.filter(i=>indices.includes(i)),rest=crop.towerPositions.filter(i=>!indices.includes(i));
 const perPot=crop.seedsSown===crop.towerPositions.length;
 const changed=normalizeSeed({...crop,id:rest.length?'seed_'+randomUUID():id,towerPositions:chosen,plantsPlanted:chosen.length,seedsSown:rest.length?(perPot?chosen.length:null):crop.seedsSown,status:args.action==='remove'?'finished':args.stage,updatedAt:now});
 if(rest.length){const retained=normalizeSeed({...crop,towerPositions:rest,plantsPlanted:rest.length,seedsSown:perPot?rest.length:crop.seedsSown,updatedAt:now});updates.push(retained);state.seeds=state.seeds.map(s=>s.id===id?retained:s);state.seeds.push(changed);}else state.seeds=state.seeds.map(s=>s.id===id?changed:s);
 updates.push(changed);for(const slot of state.plan.slots.filter(s=>chosen.includes(s.index))){if(args.action==='remove')clearSlot(slot);else slot.cropId=changed.id;}
 }
 refreshClearance(state);state.plan.revision++;state.plan.sourceHash=fingerprint(state);return{write:true,seeds:updates,value:makeView(state)};
});
export const undoTowerAction=args=>transaction(args,state=>{
 checkVersion(state,args);const undo=state.plan?.undo;if(!undo||undo.id!==args.undoId||undo.fingerprint!==fingerprint(state))fail('Other records changed. Reload and review before making another correction.',409);
 const previous=undo.plan,revision=state.plan.revision+1,receipts=state.plan.receipts;
 const restored=new Map(undo.seeds.map(s=>[s.id,s]));state.seeds=state.seeds.filter(s=>!undo.inserted.includes(s.id)).map(s=>restored.get(s.id)||s);
 state.plan=previous||{...state.plan,slots:state.plan.slots.map(s=>({...s})),items:[],undo:null};
 if(!previous){const owners=occupied(state,state.plan.shape);for(const slot of state.plan.slots){clearSlot(slot);const c=owners.get(slot.index);if(c)Object.assign(slot,{status:'growing',cropId:c.id,crop:c.crop,variety:c.variety,spacing:c.plantSpacingInches,reason:'Saved planted crop'});}state.plan.sourceHash=fingerprint(state);state.plan.profileHash=hash(state.project.systemProfile);}
 state.plan.revision=revision;state.plan.receipts={...previous?.receipts,...receipts};delete state.plan.undo;
 return{write:true,undoing:true,seeds:undo.seeds,deletedSeedIds:undo.inserted,value:makeView(state)};
});
export async function towerPlanContext(args){const view=await getTowerPlan({...args,subscription:{active:true}});if(!view.plan)return null;return {revision:view.plan.revision,staleProfile:view.stale,shape:view.shape,items:view.plan.items,positionsTruncated:view.plan.slots.filter(s=>s.status!=='available').length>80,positionCounts:view.plan.slots.reduce((counts,s)=>({...counts,[s.status]:(counts[s.status]||0)+1}),{}),positions:view.plan.slots.filter(s=>s.status!=='available').slice(0,80).map(s=>({tower:s.tower,level:s.level,face:s.face,crop:s.crop,status:s.status,reason:s.reason})),meaning:'Planned positions are not planted crops. Only growing positions have a confirmed planting record.'};}
